-- MySQL Script generated by MySQL Workbench
-- 06/08/21 19:52:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema exam
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema exam
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exam` DEFAULT CHARACTER SET utf8 ;
USE `exam` ;

-- -----------------------------------------------------
-- Table `exam`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exam`.`tasks` (
  `idtask` INT NOT NULL,
  `task` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtask`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exam`.`vremia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exam`.`vremia` (
  `idvremia` INT NOT NULL,
  `start` DATETIME NOT NULL,
  `stop` DATETIME NULL,
  `tasks_idtask` INT NOT NULL,
  PRIMARY KEY (`idvremia`),
  INDEX `fk_vremia_tasks1_idx` (`tasks_idtask` ASC),
  CONSTRAINT `fk_vremia_tasks1`
    FOREIGN KEY (`tasks_idtask`)
    REFERENCES `exam`.`tasks` (`idtask`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exam`.`parametrs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exam`.`parametrs` (
  `idparametrs` INT NOT NULL,
  `parametr` VARCHAR(45) NOT NULL,
  `inf` VARCHAR(45) NULL,
  `tasks_idtask` INT NOT NULL,
  PRIMARY KEY (`idparametrs`),
  INDEX `fk_parametrs_tasks1_idx` (`tasks_idtask` ASC),
  CONSTRAINT `fk_parametrs_tasks1`
    FOREIGN KEY (`tasks_idtask`)
    REFERENCES `exam`.`tasks` (`idtask`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exam`.`starting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exam`.`starting` (
  `idstarting` INT NOT NULL,
  `den_nedeli` VARCHAR(45) NULL,
  `vremia` TIME NULL,
  `interval` DATETIME NULL,
  `edinststart` DATETIME NULL,
  `tasks_idtask` INT NOT NULL,
  `mecetc` VARCHAR(45) NULL,
  PRIMARY KEY (`idstarting`),
  INDEX `fk_starting_tasks_idx` (`tasks_idtask` ASC),
  CONSTRAINT `fk_starting_tasks`
    FOREIGN KEY (`tasks_idtask`)
    REFERENCES `exam`.`tasks` (`idtask`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
